version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "4000:3000"

  backend:
    build: ./backend
    ports:
      - "6000:5000"
    depends_on:
      - database

  database:
    image: mydatabase-image
    ports:
      - "27017:27017"